---
title: "A Series of Plots Using NYC Restaurant Inspection Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
set.seed(1)
```

```{r clean, include=FALSE}
data("rest_inspec")
rest_inspec=
rest_inspec %>% 
  mutate(grade = forcats::fct_relevel(grade, c("A","B","C","Z","P","Not Yet Graded")), score=as.numeric((score)), camis=as.character(camis))
```
Column {data-width=650}
-----------------------------------------------------------------------

### Number of Violations by Grade 

```{r}
x= list(
  title = "Restaurant Grade")
y= list(
  title = "Number of Violations")
rest_inspec %>% 
  count(grade) %>% 
  plot_ly(x = ~grade, y = ~n, color = ~grade, 
          type = "bar") %>%
  layout(xaxis=x, yaxis=y)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Inspection Score by Borough

```{r}
x= list(
  title = "Borough")
y= list(
  title = "Score")
  rest_inspec %>%
  sample_n(1000) %>%
  plot_ly(x = ~boro, y = ~score, color=~boro,
         colors="Set2",
         type="box") %>%
  layout(xaxis=x,yaxis=y,showlegend=FALSE)
```

### Number of Violations and Mean Score for Establishments with over 25 Violations

```{r}
x= list(
  title = "Mean Score")
y= list(
  title = "Number of Violations")
rest_inspec %>% 
  group_by(camis,) %>%
  summarize(n=n(),score=mean(score)) %>%
  filter(n>25) %>%
  plot_ly(x = ~score, y = ~n, 
          type = "scatter",mode="markers") %>%
  layout(xaxis=x, yaxis=y)
```